version: '3'

services:
  hello:
    image: hello-world
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: findmark
      MYSQL_USER: findmarkuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  elasticsearch:
    image: "elasticsearch:2.4.4-alpine"
    restart: always
    ports:
      - "4200:9200"
      - "4300:9300"
    environment:
      - network.host=0.0.0.0
      - transport.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
  nginx:
        image: erichmx/findmark-nginx
        ports:
           - "80:80"
        build:
           context: ../../
           dockerfile: release/docker/nginx/Dockerfile
  crawler:
    depends_on:
      - db
      - elasticsearch
    build:
      context: ../../
      dockerfile: release/docker/crawler/Dockerfile
    image: erichmx/findmark-crawler
    ports:
      - "8080:80"
    volumes:
      - /code/findmark/src/crawler:/usr/local/tomcat/webapps/crawler:rw
      - /code/findmark/release/data:/data:rw
      - /gradle:/gradle
    environment:
      - BM_ENV
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=findmark
      - DB_USER=findmarkuser
      - DB_PASS=${MYSQL_PASSWORD}
volumes:
    db_data:
    search_data:
